### ISSUE TITLE
Super daily block has drifted almost -1 hour a day (from 24 hours) for 60 days

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#12]
Since the release of 1.4.4.x in July 2019, there's a predictable trend of daily superblock being shorter than 24 hours. In the last 60 days, the cumulative drift exceeds 54 hours (almost 1 hour per day, or 23 hour daily superblock day). 

This shift is noticed around block 130k (or when 1.4.4.x was released in July 2019). 

In chart 1, the block day drift is reset after each GSC Smart-Contract Reward block. You see that the drift is always negative (less than 24 hours for daily superblock). Before block 130k, the drift could either be positive or negative.

![image](https://user-images.githubusercontent.com/6989799/64203323-064a2380-ce48-11e9-8faf-c24722f0fcd4.png)

Second chart graphs ideal block time (86400 seconds) and does not reset each day. This allows you to see the drift from block 118100 until the present. The downward trend since July 2019 until the present is very noticeable.

![image](https://user-images.githubusercontent.com/6989799/64203266-e74b9180-ce47-11e9-95ad-2c2e2be041fe.png)

Source: data retrieved via chainz api -- https://docs.google.com/spreadsheets/d/1nQFCKW37OGElgtrb-h0borYgN8eEe2nalofMvGSQP4E/edit?usp=sharing

**Comment by biblepay** [comment]
I took a look at this issue in more detail, and I believe the explanation for clock drift in BiblePay is mostly related to our late block threshhold feature, ABN and our price.

When we did not have ABN and we had a higher price (and a higher POW reward), in that environment, I believe miners tended to pump up the difficulty and then leave us alone for a while (pump and dump).  This exploited our late block threshhold more often in DGW.  This means, we had many more fully late blocks (IE > 45 mins).

In the ABN world however, I believe our blocks are not being pumped and dumped much (because the miner must have an ABN to mine it).  Meaning that our average diff is lower (it is < 5000 now), so now we have the clock running faster because there are no late blocks to skew the average higher.

We have adjusted DGW a couple times already to compensate for the late blocks, now we see the true chronometer is actually running a little fast.

So I created a mitigation plan for the next version- we will have a master clock command, and this will allow us to easily adjust DGW from mandatory to mandatory with the exact figure stated.  The command will analyze the shorter term chronological range (IE 10% of the block duration) and the longer term, and emit the trend and then emit the consolidated adjustment.

Note that it is normal for the clock to be off (Take bitcoin for instance, they have 10 minute blocks, currently with 593,226 blocks and an expected block count of 561,314 - meaning they are off by 6% currently) - due to the random nature of mining.

What I am doing is taking a look at the big picture:  from the grand scheme, our clock has been SLOW.  (We emitted 142000 out of 169000 expected).  Now we are running fast in the short term with ABN.  So the masterclock mitigation figure will recommend that we run DGW *fast* until we near the target.

This means that technically right now, because we ran slow for 2 years and we are running fast right now, we will most likely see a cancellation and will need to take NO action for the next wallet release.  

Either way the exec masterclock command will be ready in the next release.

PS This has nothing to do with our 7 minute block target that someone mentioned is a potential problem - I stand behind that decision to have less data and less empty blocks.

**Comment by sunk818** [comment]
> Note that it is normal for the clock to be off

I read that Bitcoin [adjusts difficulty every 2016 blocks](https://blockonomi.com/bitcoin-difficulty-target-adjustment/). Isn't the benefit of [DGW ](https://www.nvestlabs.com/2019/03/13/dark-gravity-wave/) to adjust "the difficulty levels every block (instead of every 2016 blocks like Bitcoin) based on statistical data from recently found blocks"? I guess I don't see the connection between Bitcoin and BiblePay as it relates to the time between blocks and difficulty. I'm likely missing something here.

> So I created a mitigation plan for the next version

Anyway, thank you for your consideration. I appreciate you looking into this while having a very busy schedule.

**Comment by biblepay** [comment]
Bitcoin adjusts the difficulty to try to meet the future target block spacing, but as in most POW coins, a difficulty adjustment is only working on the future target and has no memory of history.  So my comment comparing BiblePay to bitcoin shows how difficulty adjustment algorithms and random heat mining solutions naturally sway from the target.  We are comparable to bitcoin because DGW is not very far from bitcoins readjustment alogorithm.
