### ISSUE TITLE
InstantSend not working - always confirms to 1 of 6

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#17]
InstantSend worked pre-evo. At some point InstantSend seemed to stop working. Any transaction I try to send (all inputs have 6 or more confirmations), will never confirm 6 of 6 on the next block confirmation. It will always be 1 of 6. I realize InstantSend is not guaranteed always, but it should work most of the times with the masternodes online.

```
Status: 3/unconfirmed (verified via InstantSend), broadcast through 7 nodes
Date: 9/21/2019 16:49
Total debit: -702 795.39167925 BBP
Total credit: 702 795.39167925 BBP
Transaction fee: -0.00376000 BBP
Net amount: -0.00376000 BBP
Transaction ID: 262b8e5253dd1bb48ab396be47da87801db7c7924311f4cd45685ded19ef9ae3
Output index: 0
Transaction total size: 375 bytes

Height: 146437
Difficulty: 3493.53
Time: 09-21-2019 23:58:25
Subsidy: 1374.2299
```

https://docs.dash.org/en/stable/wallets/dashcore/privatesend-instantsend.html#instantsend

**Comment by biblepay** [comment]
Reproduced - I confirm that I only receive one confirm after 1 block also.

Hmm, its hard to believe that no one complained about this yet.  But I believe its not being used very often right now. 

I remember when I sent BBP to Tokok I clicked instant send and it didn't go instantly and I assumed Tokok didn't accept IX, but now that I see this issue, its possible its broken.

Ill check into this.

**Comment by biblepay** [comment]
Please re-test after block 148,000 after Apollon upgrades.

**Comment by OrbisPictus** [comment]
I'ůve tried to send those my sub 1 BBP tx to myself with instantsend (all txs had more than 6 confirmations) but Instantsend failed (InstantSend authentication failed).

**Comment by biblepay** [comment]
@OrbisPictus Yes, I am having the same problem after block 148000, so I do not think its our sanctuary health (as Apollon already upgraded also).  

One thing I find very strange is - if I pick some small inputs, I can get it to instant send verify on the Sending size, but on the receive side it always says failed.

So it looks like I need to either debug this myself - or expiriment with deterministic keys.  One thing unique about the environment we are in - we are stuck in hybrid mode.  We have 48 deterministic sancs and 100~ non deterministic.  So there are a lot of places in the code that now have if-then statements!  Dash didnt intend to stay in hybrid mode for long.  Notice how fast they moved from .13 to .14.  We are stuck because we cant move to .14 with chain locks until we have a solid plan for our sancs to *all* become deterministic at once.

So let me try to determine next if its a hybrid issue, first.

**Comment by sunk818** [comment]
Will be block 148309. I sent payment to myself using InstantSend (on 6 confirmed input).

Just have question ? instead of 5/6 confirmations.

![190930-1206](https://user-images.githubusercontent.com/6989799/65908201-ca3cac80-e37a-11e9-95ba-a8fc2aaefd2b.jpg)

```
2019-09-30 19:00:30 CommitTransaction:
CTransaction(hash=20598e0359, ver=1, type=0, vin.size=1, vout.size=1, nLockTime=148262, vExtraPayload.size=0)
    CTxIn(COutPoint(f06e3e49ad4f3b050cc2ae9e5fef69b200c693344625438f960b3862869a3324, 0), scriptSig=4730440220708a715107c4d7, nSequence=4294967294)
    CTxOut(nValue=3047.62174818, scriptPubKey=76a91447a5bbeef63ab6c69abf81f6)
2019-09-30 19:00:30 CInstantSend::CreateTxLockCandidate -- new, txid=20598e035923b55ce0e3d900aec76c80bae40465155c5ed1e570d40e8474ec5d
2019-09-30 19:00:30 CInstantSend::ProcessTxLockRequest -- accepted, txid=20598e035923b55ce0e3d900aec76c80bae40465155c5ed1e570d40e8474ec5d
2019-09-30 19:00:32 Consensus::ContextualCheckBlock::TestBlockValidityLite  (code 0)Consensus::ContextualCheckBlock::TestBlockValidityLite  (code 0)

```

**Comment by biblepay** [comment]
@sunk818 Yes, I see that, and whats the question?  (I see that it appears like a normal transaction) - are you asking why it does not appear as 6 immediately?  If thats the question its because IX is not handled in the GUI properly - and we need a code release.  Im still testing the change in Testnet, but I believe at this early stage - IX works and all we have is a cosmetic problem.  (Although I do believe we need a longer timeout on each IX sig, and, a different quorum size in prod to make IX reliable).

**Comment by sunk818** [comment]
No question. I'll just thumbs up @OrbisPictus and related my comment. It is just a me too!

**Comment by biblepay** [comment]
I think our last release only resolved half of the problem; part of the problem is Dash has 4500 masternodes while we have 150.  So they want 25 sigs in certain circumstances and we apparently cant sign 25 in only 60 seconds with our small farm.

Let me look into the quorum size next.

**Comment by biblepay** [comment]
I modified TestNet in 1.4.7.6 to give us more time before expiration.  Lets test this in the next version in testnet.

**Comment by biblepay** [comment]
Fixed.
