### ISSUE TITLE
ABN improvements

### ISSUE THREAD

**Issue by OrbisPictus** [biblepay/biblepay-evolution#20]
Hi,
I have few sugestions to change ABN behaviour (if it would be possible):
1. After each mined block it creates ABN tx, what is good, but after each tx there remains cumulative ABN tx and <1BBP tx. I have tons of these small txs (https://prnt.sc/pbcrmg) which I think is not desirable. It would be nice if there will be only one cumulative tx.
2. Change ABN tx behaviour to same as GSC tx. To divide it to smaller bankrolls, eg. with changequantity or to exact eg. 125000 BBP bankrolls (or smaller).
3. Change ANB tx creation. I know that it still starts with coins with lowest coinage, but sometimes it's not "good". Eg.: you have 1M BBP bankroll with weight 60k, second bankroll 1M BBP with 60k weight and 125k BBP bankroll with 180k weight. Current algorhitm take all of your bankrolls and combine it to one ABN tx with 2,25M BBP and 300k weight even if it will be enough to take bankroll with 125k BBP.

Take it just a suggestions what could help someone (someone like me :)). Thanks.

**Comment by sunk818** [comment]
> 3\. Current algorhitm take all of your bankrolls and combine it to one ABN tx with 
> 2,25M BBP and 300k weight even if it will be enough to take bankroll with 125k BBP.

I commented same thing two months ago, but dev made no comment about it. The behavior I noticed back then, like you said was because of same input amount. I haven't tested with latest version, but this may already be fixed. Is it still same with 1447o? 

https://github.com/biblepay/biblepay-evolution/commit/6d76ad8222962d35c1b3af91911241615797cf4b#commitcomment-34325822

**Comment by biblepay** [comment]
@sunk818 No, when you commented on the pasted commit, you inferred that we were using duplicate inputs (which is not correct because we dont duplicate inputs).  You also posted 6 other things (IE spam).  I recommend consolidating them into one issue and entering a github issue (not questions about things you are "speculating" in code comments).

Orbis is recommending that we sort the inputs by age first in # 3.  Which I believe we do - but maybe we dont in ABN's, Ill have to look at this issue when we get to this ticket.

**Comment by OrbisPictus** [comment]
> Orbis is recommending that we sort the inputs by age first in # 3. Which I believe we do - but maybe we dont in ABN's, Ill have to look at this issue when we get to this ticket.

I'm sure that it doesn't work for me. It's enough to take a look through exec getabnweight a you'll see that it doesn't sorts it by age. It'll be best to take 1st package with 125k weight. 

> Is it still same with 1447o?

I'm still trying to have newest wallet version on all of my miners, but I'm using pre-compiled binaries and I'm not able to find out which version I have, because those "letters" version (1447a,b,c, ...) are not visible in getinfo. 

> I like how clear this tickets requirements are.

Thanks

**Comment by biblepay** [comment]
The new version 1448 is almost out - but in the mean time, let me take a look at sorting for ABNs.

**Comment by biblepay** [comment]
Hi Orbis,

So on # 1 and # 2, I believe we can do something there - modify ABN "change" handling to not create change < 1 bbp, and, provide multiple outputs for people who break big bills.

Moving on to # 3 however, I did a test yesterday with 'exec getabnweight 125000 1', and I see that we already *do* sort by coin-age before selecting the inputs.  We sort the entire wallet by coin-age ascending, then we select the least amount of coin age possible - in order.  Could you please do a re-test on # 3 and confirm that # 3 is not an issue?

**Comment by OrbisPictus** [comment]
Thanks.
Ok, now I have only one huge package, but I'll try to install 1148, make exec bankroll and test it. I'll post my results here.

**Comment by OrbisPictus** [comment]
I was thinking that I won't be able to reproduce it, because I've had a luck and hit two blocks :) , but here is my actual result of `exec getabnweight 125000 1`:
```
  "Command": "getabnweight",
  "version": 2.7,
  "weight": 205778.0359606482,
  "total_required": 2867711,
  "coin_age_data_pre_select": "999999.0200(0.03)=[32928.21] depth=11,  <ROW>1867712.3384(0.09)=[172849.83] depth=23,  <ROW><TOTALREQ>2867711.36</TOTALREQ><TOTALAGE>205778</TOTALAGE>",
  "weight 125000.00": 205778.0359606482,
  "total_required 125000.00": 2867711
```
You can see, that even if the second package would be enough ABN will use the first one "uselessly" instead of letting him mature.

**Comment by biblepay** [comment]
@OrbisPictus Ok, you are referring to using the small input first and then the bigger input - because we told it to sort by coin-age ascending - which covers the biggest part of the use case (not wasting extremely large ages).  Take a situation where someone has ten 1 million coin age coins and one 200K coin-age coin.  It would sort these by coin-age ascending.  So it would use the 200K coin first, be satisfied and break out (and not waste the users large coin age).

In your case you are saying you dont like it using up the 32K first then the 172K because that spends 204K - and does not preserve the 32K.  But even if we used the 172K we would have wasted 50K anyway (by going over by 50K).  

So it is designed like this for a reason - to use up the smallest coin age first before tapping into the bigger coin age.  Its not a good idea to make this so complicated that no one will be able to support the code.

Asking us to modify the "change" emitted to be more plentiful sounds like it will address this anyway.  If we give you change of an adjustable quanity (IE 25 tx's of change from an ABN, a broken bill will end up being more like 5K change * 25 quantity) meaning the code as is would sort by coin-age ascending and use up more of the small ones first, satisfying the requirement without tapping into your bigger ones.

So Ill keep looking into # 1 and # 2 very soon.

**Comment by biblepay** [comment]
So, Im starting to look at implementing # 1  and #  2, and I have a question.  In my wallets case, I send ABNs occasionally into the pool, and because we sort coin-age ascending, my GSCs consume my .98cent (IE sub-1 bbp) transactions regularly, because the GSCs use up that small coin-age first.  So in my case I only have one .99 bbp in the whole wallet.  Question, what wallet version were you using that was piling up many sub 1 bbp tx?  Was this a very old wallet?  (As Im assuming this shouldnt be happening with the coin-age ascending rule).

Ill move on to # 2 in the mean time.

**Comment by OrbisPictus** [comment]
On #3: If it is designed like this for a reason, leave it like it is. I don't like it, but it's only my opinion :)
On #1: I'm using always newest versions of wallets. These sub 1BBP tx are creating in 1148 too.  After every hitted block. ABN tx is everytime divided to ABN weight consuming tx and sub 1 BBP.

**Comment by biblepay** [comment]
I'm confused on # 3 though, you don't like it, but its there to protect your coin age (we use the smallest coin age first).  I explained how we went out of our way to sort the entire wallet by coin-age ascending before touching your coin age.  Are you saying you would rather we sort it, then scan it, then if we find one transaction we match it (out of order) then loop back and start over with ascending then loop again?

On # 1, could you please paste your 'exec getabnweight 125000 1' so I can see if you are including the sub 1 bbp tx in your getabnweight selector?  If you have all these in the wallet, they are supposed to be first in that resulting selection output?

**Comment by OrbisPictus** [comment]
On # 3: Yes, it's like you wrote.... My experience was that everytime I've made exec bankroll, my coins was  slit into one package in less than 6 hitted (by me) blocks. So I'm mining most of the time with one huge package. I was trying to made exec bankroll, then not to mine for one day (to reach coinage), but after 3 days I was on the same. SO, yes, my problem is that most of my coins was with coinage less than ABN requirement. But I hope, that it'll be better with 1149 and implemented changequantity (Thanks for that :) )

On # 1: I think it's not needed to paste exec getabnweight, because those sub 1 BBP txs are not included getabnselector (never). Now I have 35 of those txs. Time to time I sent them to my wallet.

**Comment by biblepay** [comment]
On # 3, OK great, so 1149 should fix that as more quantity of change works its way through the system , OK good.

Now on # 1, these sub 1 transactions are included in ABNs or GSCs  (thats how they get consolidated and get used up).  The rule for GSCs/ABNs is :  Dont spend sanctuary funds, dont spend locked funds, dont spend more than 500 inputs, and Do sort by coin-age first, then pull them in.  So as long as you have less than 500 wallet transactions, you should be picking them up in the exec getabnweight 125000 1.  If you arent, just try -zapwallettxes=1 and restart (or rescan your wallet) and try again.  Or just spend them back to yourself once, and verify after that they do get included in ABNs.  They should be- so technically nothing to do on # 1, then we can close the ticket?

**Comment by OrbisPictus** [comment]
I've made -zapwallettxes=1 more than once before, but they've never been in my ABN tx. Nevermind. I'll send them to myself and they'll be gone :)
Thanks for all. I'm closing this ticket.

**Comment by OrbisPictus** [comment]
@biblepay those sub 1 BBP txs are still creating after hitted block in 1149: http://prnt.sc/pcyb04
but changequantity  is working 👍

**Comment by sunk818** [comment]
Need clarification on changequantity. If we set changequantity=9 in biblepay.conf is this honored when change is created after an ABN transaction (a block is mined)?

**Comment by sunk818** [comment]
> On # 3, OK great, so 1149 should fix that as more quantity of change works its way through the system , OK good.

The default is 10? the `changequantity` entry in `biblepay.conf` does not affect how much change is generated after a mined block?

**Comment by sunk818** [comment]
@OrbisPictus If change can be added to one of the outputs or allow <1 BBP be used as ABN input, then we won't have any small change.

**Comment by OrbisPictus** [comment]
@sunk818 I don't know where is problem, but all of my "small" balances are still included in ABN input except those sub 1 BBP. So I don't have any small change. Every new hited and aged block is included into ABN. So in my wallet are only those sub 1 BBP and bannkrolls from ABN. If those sub 1 BBP txs are expected I don't have problem to send them time to time to myself.
And yes, it works with changequantity=X in biblepay.conf

**Comment by biblepay** [comment]
I don't think we have a rule, but, if its doing again for you, Ill check more thoroughly all the rules now.

**Comment by OrbisPictus** [comment]
Does it mean that this happens only to me? Has anyone else this problem?

**Comment by togoshige** [comment]
I have a wallet that only POBH/ABN mines and I also get a lot of 0.99* amounts

**Comment by biblepay** [comment]
I'm checking the rules to see how this can happen.

**Comment by sunk818** [comment]
Is this irrelevant now that is ABN is turned off? I think we can all live with 0.99 change as output.

**Comment by OrbisPictus** [comment]
I agree. I think, it can be closed. Thanks.
