### ISSUE TITLE
One Click Mining Configuration corrupts biblepay.conf

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#21]
This in reference to old issue about [corrupt biblepay.conf](https://github.com/biblepay/biblepay/issues/36).

Using 1.4.4.9 on macOS, I erased `biblepay.conf` and started BiblePay-QT

Went into Tools, select One Click Mining Configuration

![image](https://user-images.githubusercontent.com/6989799/65903621-9ad57200-e371-11e9-9992-efa48a3b1c7c.png)

Then Click OK on warning

![image](https://user-images.githubusercontent.com/6989799/65903510-6661b600-e371-11e9-840f-14c5452d3045.png)

Looked at created file using hex fiend for macOS:

![image](https://user-images.githubusercontent.com/6989799/65903168-c99f1880-e370-11e9-91fd-d00866c9e114.png)

**Comment by biblepay** [comment]
Good find, what Mac OS is this exactly?

I think we need a code change with an additional moniker - we currently only have linux/windows monikers - but we can add one for OSX.

So whats happening above is we are treating your Mac like "linux" - emitting each line with a "0A" between each line, instead of the specific MAC lfcr.  I believe mac needs lfcr, windows crlf, and linux lf.  We current have :  crlf OR LF in the code only (we need 3 and we have 2).

**Comment by sunk818** [comment]
The convention for macOS 10.x and on follows Unix which is the [0x0A or line feed. ](https://community.perforce.com/s/article/3096). 

Please disregard, after further testing, macOS BiblePay-QT wallet seems to process `biblepay.conf` with either line ending with either CRLF or LF. 

I got confused thinking macOS needed 0x0D 0x0A like Windows, but I don't think it matters in the latest version 1.4.4.9.

**Comment by sunk818** [comment]
Sorry, I have to re-open issue because after testing on Windows 10, look at the biblepay.conf from One Click Miner Configuration. The line ending is 0x0D 0x0D 0x0A

![191002-21](https://user-images.githubusercontent.com/6989799/66097059-de86d200-e551-11e9-8f84-64a0ab000b15.jpg)

**Comment by biblepay** [comment]
So far, my tests have been successful on windows and linux.
We may need to pull MIP in on this because I dont have a mac.

MIP, can we test this in the testnet branch?

I have an easy test case.  The latest wallet 1.4.6.7 stores the PursePrivKey in the biblepay.conf file using this same function; can you please set up your purse priv key and see if your external wallet sends a tx without an error?

**Comment by sunk818** [comment]
@biblepay @MIPPL On testnet every time an external purse creates a private key, the line ending is encoded as macOS according to Notepad++

**Comment by sunk818** [comment]
this still an issue and I'm sure anyone needing to create an external purse will have a harder time with this unresolved

**Comment by biblepay** [comment]
MIP tested it and it works on Mac, so I have no evidence its broken anywhere.

**Comment by sunk818** [comment]
yes problem is with windows 10. for example when you created external purse entry the line ending is wrong for windows
