### ISSUE TITLE
Give users more control of how ABN splits utxo for mining

### ISSUE THREAD

**Issue by NickP1** [biblepay/biblepay-evolution#25]
The automatic splitting of utxo by ABN needs to give us a bit more control over it as it affects our mining.
It should be improved or removed.

A person should have to give permission to enable abn to split utxo.
"changequantity=" is not enough control.
We should be able  to turn it on/off, dictate size of utxo and number of utxo, even set to -1 to enable "numberofUTXO=(balance-2bbp)/desiredUTXOsize" rounded down to the nearest whole number. The 2 bbp ensures there is always enough available for fees.
And it still takes coin weight from lowest to highest, lumping previously used utxo in every increasing lumps.
Sorting utxo to find the ideal number of utxo coin age to use might be a good way to go.
Such as fewest utxo to reach required coinage starting with highest coinage utxo first.
After all, large utxo shouldn't be a problem as they are auto split into smaller utxo.
 
suggested conf settings:
enableabnsplit= 0 or 1 and default to 0
abnsplitsize=2000 to X and default to -1
minabnutxos= 0 to turn off minimum and 1 to maximum 100 will provide that many utxo and leave any remaining untouched or as change, override by "abnsplitsize=-1"

Alternative is turning it off completely and using a custom script to control utxo splitting based on abnweight which I do already. Although I cannot prevent ABN from splitting automatically every single time I get hit for ABNweight.

**Comment by sunk818** [comment]
> The automatic splitting of utxo by ABN needs to give us a bit more control over it.

You have not explained why having control over ABN splitting is necessary. How is adding complexity to the current process going to improve your situation?

Could you also edit your title and body and create separate issues or suggestions? You are conflating multiple ideas into one.

**Comment by NickP1** [comment]
how do you see this as multiple issues?! and it has been edited

**Comment by sunk818** [comment]
> And it still takes coin weight from lowest to highest, lumping previously used utxo in every increasing lumps.

In 1.4.4.9, your oldest coins are preserved by utilizing your newest coins first. It will just continue to use your newest coins to make up whatever it needs for abnweight of 125k BBP. You'd have to explain taking a single input from an older coin (to exceed 125k BBP abnweight) is better than just taking 10 of the most recent coins.

Optimally, you'd want to take input(s) that brings you closest to 125k BBP without going over. I do see some downsides to taking the youngest coin age first, but in practice, splitting the change into 10 outputs instead of 1 is a vast improvement. The next time you mine a block, instead of taking that single input, it might take 3 of the 10, leaving the other 7 for future mined blocks.

BiblePay is already complex with its various settings. I don't see the slight improvement justifying the added complexity and documentation required. This is JMHO.

**Comment by NickP1** [comment]
Seeing as the ABN Auto spits the tuxos already, large utxos are already made into small ones. As explained in the OP. Taking from highest coinage allows lowest coinage time to age.
Everytime you get hit for abnweight the wallet is now taking lowest coinage to create the abn amount and then splitting into 10 pieces by default. the next time it needs to create an abn amount it  takes from the utxos it split the last time and lumps it altogether and then splits it AGAIN. This is counter productive to aging coins for mining.
I am not trying increase the complexity, I followed the guidelines for submitting an issue best I can. Removing the automatic splitting is fine too or at the very least give us an on/off switch.

**Comment by NickP1** [comment]
Also, for your info, pool mining self funded can take out 1.25 Million ABNweight in 10 blocks without your machines ever finding a block. 
This is vastly different than solo mining.

**Comment by sunk818** [comment]
> This is counter productive to aging coins for mining.

In the long-term, it doesn't really matter whether you take the youngest coins or oldest coins for abnweight. If you take the oldest coins first, your youngest coins will become the oldest and vice versa. The greater impact is when an input is so large that abnweight greatly exceeds 125k BBP. That is what splitting it 10 ways addresses.

If you can not continuously mine then you starved for abnweight. The only way to fix this is to reduce your hash power or get more BBP. Changing how UTXOs are picked will only have a one-time benefit. 

If you disable abn splitting, you are in a far worse position than now. You just have to look at the blockchain data before 1.4.4.9. You will find high hash miners unable to mine because all their BBP is tied up in one input. They end up having 30 minute or longer gaps between blocks because they have no eligible abnweight. Some resorted to `exec bankroll` of 125k BBP, but who has time to babysit BBP wallet for mined blocks?

> This is vastly different than solo mining.

Your abnweight happens to be used with someone else's hash power, but there's no difference with the abnweight mechanics between solo mining and pool mining.

**Comment by NickP1** [comment]
There is no difference in the mechanic, just the experience as others are using up your abnweight and thereby increasing virtually your hashing power. It has happened that all 1.25 Million abnweight that I aged during the week was taken in 14 blocks by other pool users.
In any case, we should have the choice to enable/disable auto splitting regardless of whether or not it's "good" for us.
I don't babysit my coins so I can bankroll them. My script does that quite nicely on it's own. The auto splitting just does unnecessary additional splitting.

**Comment by OrbisPictus** [comment]
As a miner I can say, that ABNsplit helps me a lot with my coinage. It's really better then before 1149. Maybe you can try to use changequantity=1 if you want only 1 output, but I think that it's counterproductive, because like Sunk wrote "it might take 3 out of the 10, leaving the other 7 for future mined blocks"

**Comment by NickP1** [comment]
@OrbisPictus you don't have a script that manages the abnweight like I do. This is also about permissions. We should be allowed to enable/disable it

**Comment by OrbisPictus** [comment]
Ok. You're true, I don't have any script, because I don't need it. Haven't you problem with GSCsplit before? Or you don't use it for GSC?

**Comment by NickP1** [comment]
I do not use GSC anything. no point with such a low balance. I only PoBH mine.

**Comment by biblepay** [comment]
Hi All,

I just want to clarify something :  We don't sort the wallet by the age of the coins or by the value of the coins.  What we do is we have a custom sort routine (for both ABN and GSC, they both use the same sort routine), and its called "coin * age".  This is to attempt to appease *mostly* everyone LOL.  

So, if a person has a sufficient amount of change (IE say, 20 transactions in the wallet), this is what happens:  No matter what the coin *amount* is, or the *age* is, the custom sort routine calculates the coin*age of each wallet entry, and sorts *ascending*.  So in either case, abn or gsc, we use up the *smallest* coin*age first when selecting coins for the abn/gsc transaction.

The other thing, although I agree with Sun, that we do not want to complicate the wallet with a lot of settings as we easily get overcomplicated, I also agree with Nick that at the very least the user should always have control over their funds/wallet/actions of bbp.   But visualizing a switch to disable the change is really the same effect of "changequantity=1" ;  as we always have to send you the change back from a transaction.  

So Nick, do you agree that all that really needs done on this ticket is the user set "changequantity=1" ?

I see Orbis suggested this as his last suggestion; let me know Nick if there is anything else we need to do here.

Thanks!

**Comment by NickP1** [comment]
I agree that changequantity=1 is a solution to controlling whether or not ABN splits utxo. Perhaps when things are not so busy it can be revisited as to how it sorts coin * age and chooses coins for the transactions.
Also it would be good if settings like this were available in a help file or in the debug console.
Thanks for  clearing this up :)
