### ISSUE TITLE
GSC Transmission for CameroonONE occurs even with -1

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#26]
If I have the following setting, I expect the other GSC campaigns to work, but not CameroonONE. 
```
disablegsctransmission=0
cameroon-one_foundationdonation=-1
cameroon-one_coinagepercentage=-1
```

It seems if gsc transmission is enabled, CameroonONE ignores the -1 setting and sends a tithe every 12 hours.

**Comment by biblepay** [comment]
I've been looking at the code, and I see you have the correct syntx for "campaign-name_coinagepercentage" in, and from what I see its supposed to exit (even when called by the miner) with: Sorry, no coins available for a GSC Transmission. (A very vague error but designed for the case where the coinagepercentage * available coin age is < 1 coin)

Then I added a function to the code to ensure its reading the "cameroon-one" setting, and it is.

So, instead of debugging this matter longer, I added a new block to specifically check for the "_coinagepercentage=-1" - and now we will honor that and exit with : User has disabled this campaign [" + sCampaign + "] via coinagepercentage=-1.

So please try again when we release 1.4.5.1.

**Comment by sunk818** [comment]
The biblepay.conf settings for the following settings in 1.4.5.1 seems to be working. Thank you for the fix!

```
cameroon-one_foundationdonation=-1
cameroon-one_coinagepercentage=-1
```
