### ISSUE TITLE
wcg.rac file is corrupted

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#31]
There's bad data in the wcg.rac

There's repeated string values 1000 in the file which may be causing parsing errors.

Based on my observation, I think when user.xml is being processed, it lands in our biblepay san/wcg.rac as a corrupt file.

For example:

oncoapop3 showed a RAC of 171000446.350588 yesterday.

It should have been 17446.

and the wcg.rac file was encoded partly as having line endings with CR only (macOS) as line ending.

He worked around the issue by restarting the server. I think quitting biblepay, erasing wcg.rac in san folder, and restarting biblepay will also work

```
<user>

 <id>1072773</id>

 <name>oncoapop</name>

 <country>CANADA</country>

 <create_time>1533274493</create_time>

 <total_credit>4958657.778454</total_credit>

 <expavg_credit>17

1000

446.350588</expavg_credit>

 <expavg_time>1578311975.659187</expavg_time>

 <cpid>168c62b82fb40fa3db0d34605439daa5</cpid>

 <teamid>35006</teamid>

</user>
```

![image](https://user-images.githubusercontent.com/6989799/71907047-189edb80-3120-11ea-8607-2d277206641d.png)

![image](https://user-images.githubusercontent.com/6989799/71907236-78958200-3120-11ea-8dbe-bcbb46fc19a3.png)

The XML from the WCG stats download site doesn't have this issue:

https://download.worldcommunitygrid.org/boinc/stats/

![image](https://user-images.githubusercontent.com/6989799/71907659-518b8000-3121-11ea-96da-2cfde27b61ec.png)

---

What else?

There are some XML records that are not parsed correctly.

226381 - shows all xml attributes
283635
397932
888260 - randrews :)

---
Comparing from today noon and today from 7pm. You can see bbpminer4's cpid was split apart by the 1000 injected string. Are you using curl by chance and getting the HTTP headers and output?

![image](https://user-images.githubusercontent.com/6989799/72127720-7d775300-3325-11ea-9029-886cf1e1e783.png)

**Comment by sunk818** [comment]
What else...

There are some XML records that are not parsed correctly.

226381 - shows all xml attributes
283635
397932
888260 - randrews :)

**Comment by sunk818** [comment]
Do you know this is in the wcg.rac file?

The `1000` string appears every 4096 bytes.

Are you using CURL to retrieve the file? Perhaps turning off http headers and getting the binary file will help.

People are also reporting their CPID are sometimes missing (bbpminer4, barton26) from the leaderboard.

> HTTP/1.1 200 OK
> 
> Date: Fri, 10 Jan 2020 14:02:45 GMT
> 
> Server: Kestrel
> 
> Transfer-Encoding: chunked
> 
> Expires: Fri, 10 Jan 2020 14:32:45 GMT

**Comment by biblepay** [comment]
Actually, whats interesting is when Oncoapop e-mailed me about this, I took a look at this issue from a different perspective and made the assumption that we had a one time 1000 injected for a different reason; I was not aware the 1000 marker was injected every 4096 bytes.  I just pulled the data today out of my SAN directory and saw the repeated injection.  Thanks for bringing this to my attention.

So the problem is actually, and fortunately not related to biblepays core wallet, or related to the WCG source data.

The problem is that I parse the applicable XML data in by team and eliminate those with non-bbp rac using .netcore, which a cross platform version of .net, because this is the middleware that BMS (DSQL) is written in.  Well it turns out that aspnetcore by default does not have the ability to chunk http responses (it chunks them only one way, with an incompatible buffer).

So what I had to do is add a class of chunking middleware to the dsql server so its responses will be like other web servers, and that did fix the problem.

Please restart the core wallet and now I see looking at wcg.rac the file no longer contains the 1000 markers!

**Comment by sunk818** [comment]
1) 1000 every 4096 bytes are gone
2) did you change the teams extracted by chance? pollux and barton26 on gridcoin team are missing from the list. They were there yesterday.

**Comment by biblepay** [comment]
Items in the bad news list are incorrect.

**Comment by sunk818** [comment]
> Items in the bad news list are incorrect.

#2 wcg.rac is a moving target but I assure you 4 days ago this was the case.
You can review the zip file yourself here:

https://whitewalr.us/wp-content/uploads/2020/01/wcg.zip

#3 is still present. If the wallet parses the XML correctly, its a non-issue. Just takes up more bandwidth and slightly more processing time reading the disk I suppose.

#4 I'll edit 4 out

**Comment by biblepay** [comment]
- The wallet always has parsed the XML data correctly.
- Please provide an example CPID that you claim is missing in your whitewalrus file.  
- Lets not dwell on bandwidth or the size of the XML.  There is a plan in place for that and the current size is within the parameters.  If it was not acceptable it would not have been rolled out this way.

**Comment by sunk818** [comment]
Someone who is not able talk intelligently somehow figured out the root cause of a leaderboard points issue. You could just say file size is by design and won't be fixed. No one needs to know your upcoming to-do list. You're not the only person who has things to do.

**Comment by biblepay** [comment]
The process is not faulty at all - its just not understood properly in your analysis here.

Please do not be disrespectful on our public forums.
